package dev.angussoftware.app.blog

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Tests for BlogPost data class generated methods (toString, equals, hashCode, copy).
 * These exercise compiler-generated bytecode that Kover measures.
 */
internal class DataClassTest {
    @Test
    fun blogPost_equals_sameValues() {
        val a = BlogPost(id = "1", title = "T", url = "U", pubDate = "D", summary = "S", imageUrl = "I", content = "C")
        val b = BlogPost(id = "1", title = "T", url = "U", pubDate = "D", summary = "S", imageUrl = "I", content = "C")
        assertEquals(a, b)
        assertEquals(a.hashCode(), b.hashCode())
    }

    @Test
    fun blogPost_equals_differentValues() {
        val a = BlogPost(id = "1", title = "T", url = "U", pubDate = null, summary = null, imageUrl = null, content = null)
        val b = BlogPost(id = "2", title = "T", url = "U", pubDate = null, summary = null, imageUrl = null, content = null)
        assertNotEquals(a, b)
    }

    @Test
    fun blogPost_copy_createsEqual() {
        val original = BlogPost(id = "1", title = "T", url = "U", pubDate = "D", summary = "S", imageUrl = "I", content = "C")
        val copy = original.copy()
        assertEquals(original, copy)
    }

    @Test
    fun blogPost_copy_withChanges() {
        val original = BlogPost(id = "1", title = "T", url = "U", pubDate = "D", summary = "S", imageUrl = "I", content = "C")
        val modified = original.copy(title = "New Title")
        assertEquals("New Title", modified.title)
        assertEquals(original.id, modified.id)
    }

    @Test
    fun blogPost_toString_containsFields() {
        val post = BlogPost(id = "42", title = "My Post", url = "https://example.com", pubDate = null, summary = null, imageUrl = null, content = null)
        val str = post.toString()
        assertTrue(str.contains("42"))
        assertTrue(str.contains("My Post"))
    }

    @Test
    fun blogPost_componentN_destructures() {
        val post = BlogPost(id = "1", title = "T", url = "U", pubDate = "D", summary = "S", imageUrl = "I", content = "C")
        val (id, title, url, pubDate, summary, imageUrl, content) = post
        assertEquals("1", id)
        assertEquals("T", title)
        assertEquals("U", url)
        assertEquals("D", pubDate)
        assertEquals("S", summary)
        assertEquals("I", imageUrl)
        assertEquals("C", content)
    }
}
